name: CI

on:
  push:
    branches: [ main ]
    
jobs:

  build:
    env:
      DATABASE_URL: ${{ secrets.DATABASE_URL }}
      SERVER_PORT: ${{ secrets.SERVER_PORT }}
      AUTH_SECRET: ${{ secrets.AUTH_SECRET }}
    runs-on: ubuntu-latest    
    steps:
      - uses: actions/checkout@v3
      
      - uses: actions/checkout@v2
      
      - name: setup node
        uses: actions/setup-node@v2
        with:
          node-version: 16.x
        
      - name: install dependencies
        run:  yarn
        
      - name: prisma generate
        run:  yarn generate        
      
      - name: build      
        run:  yarn tsc
        
      - uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          source: "., !node_modules"
          target: "colleges"
                    
      # - name: update api      
      #   uses: appleboy/ssh-action@master      
      #   with:
      #     host: ${{ secrets.SSH_HOST }}
      #     username: ${{ secrets.SSH_USER }}
      #     key: ${{ secrets.SSH_KEY }}
      #     port: ${{ secrets.SSH_PORT }}          
      #     script: cd colleges && yarn && yarn generate && pm2 restart colleges      
