name: CI


on:
  push:
    branches: [ main ]

jobs:
  build:  
    runs-on: ubuntu-latest    
    steps:
      
      - uses: actions/checkout@v2
      
      - name: setup node
        uses: actions/setup-node@v2
        with:
          node-version: 17.x
          
      - name: install libs
        run:  yarn
        
      - name: prisma generate
        run: yarn prisma generate
        
      - name: build
        run: yarn tsc
        
      - uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          source: "., !node_modules"
          target: "films_apimatch_dog"        
